-- fix: check-in, check-out
ALTER TABLE booking
MODIFY COLUMN status ENUM('PENDING','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED');

ALTER TABLE `room`
  MODIFY COLUMN `status` ENUM('AVAILABLE','BOOKED','OCCUPIED','MAINTENANCE','CLEANING') DEFAULT NULL;
