<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_room</name>
   <tag></tag>
   <elementGuidId>192040cb-3c2e-4d94-ac81-2f881b455995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.relative[href=&quot;\/rooms&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'PHÒNG')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Phòng&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20f30a9a-b138-4513-a961-b82a8c7a8d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rooms</value>
      <webElementGuid>902f5789-f70b-485b-a8b2-d48fe4658ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-black uppercase text-[11px] tracking-[0.15em] transition-all duration-300 relative py-2 text-white/70 hover:text-emerald-400</value>
      <webElementGuid>71fc312c-cd14-4bef-9197-bae8a30d993a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phòng</value>
      <webElementGuid>3095c3ac-15c3-4fe6-a0f8-cbd0c2df06e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-70833d94c34a1bfbf00d56d6a032471f</value>
      <webElementGuid>1c4b9e9f-1d8b-472b-b0cf-4ceea1ecc190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class and contains(concat(' ', normalize-space(@class), ' '), ' relative ') and (@href = '/rooms')]</value>
      <webElementGuid>55b4f130-0b4c-4275-99e8-eaf47742d3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@class and contains(concat(' ', normalize-space(@class), ' '), ' relative ') and (@href = '/rooms')]</value>
      <webElementGuid>1fd53ddb-32a5-4506-a0f3-349e2e355642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/rooms' and (text() = 'Phòng' or . = 'Phòng')]</value>
      <webElementGuid>39598524-c000-4a8c-822a-076fd68a807b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
