<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_room</name>
   <tag></tag>
   <elementGuidId>60470da6-b392-47c0-905f-5d500acd4d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'Phòng')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.relative[href=&quot;\/rooms&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Phòng&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf416f22-fd68-4549-b0c0-7657e6a78111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rooms</value>
      <webElementGuid>c538ba29-5526-470a-ad86-b5cc2ff42e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-black uppercase text-[11px] tracking-[0.15em] transition-all duration-300 relative py-2 text-white/70 hover:text-emerald-400</value>
      <webElementGuid>4549911b-7dc8-4177-aed4-e01369eac3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phòng</value>
      <webElementGuid>57d67524-d7d3-4fc7-a058-170c1c92a353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-70833d94c34a1bfbf00d56d6a032471f</value>
      <webElementGuid>f1bf8976-feb5-4f27-9552-8bb4be87344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class and contains(concat(' ', normalize-space(@class), ' '), ' relative ') and (@href = '/rooms')]</value>
      <webElementGuid>ba29f01e-73ac-4e73-8ce6-7605fb79b2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@class and contains(concat(' ', normalize-space(@class), ' '), ' relative ') and (@href = '/rooms')]</value>
      <webElementGuid>1282d52e-07c2-44d4-bf92-e43f0e905f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/rooms' and (text() = 'Phòng' or . = 'Phòng')]</value>
      <webElementGuid>760d2c03-ab53-4fd1-8cdc-0d9dbfb2fb8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
